#!/bin/sh 

DOTFILES="git@github.com:CPWeaver/dotfiles.git"
CMDS="git"

# Check for necessary commands
for cmd in $CMDS; do
  hash $cmd >/dev/null 2>&1 || {
    echo "$cmd command not found. Please install $cmd."
    exit 1
  }
done

# Install Homeshick
if [ ! -d "$HOME/.homesick/repos/homeshick" ]; then
  echo "Installing Homeshick to manage dotfiles..."
  git clone git@github.com:andsens/homeshick.git $HOME/.homesick/repos/homeshick
  source "$HOME/.homesick/repos/homeshick/homeshick.sh"

  # Install dotfiles
  homeshick clone $DOTFILES
  homeshick symlink dotfiles
fi

# Setup TPM
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  git clone git@github.com:tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi

hash brew >/dev/null 2>&1 || {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}
