#!/bin/sh 

DOTFILES="https://github.com/CPWeaver/dotfiles.git"
CMDS="git"

# Check for necessary commands
for cmd in $CMDS; do
  hash $cmd >/dev/null 2>&1 || {
    echo "$cmd command not found. Please install $cmd."
    exit 1
  }
done

# Install Homeshick
if [ ! -d "$HOME/.homesick/repos/homeshick" ]; then
  echo "Installing Homeshick to manage dotfiles..."
  git clone git://github.com/andsens/homeshick.git $HOME/.homesick/repos/homeshick
  source "$HOME/.homesick/repos/homeshick/homeshick.sh"

  # Install dotfiles
  homeshick clone $DOTFILES
  homeshick symlink dotfiles
fi

# Setup TPM
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi

if type defaults >& /dev/null; then
  # setup iterm2 profile
  # Specify the preferences directory
  defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/.iterm2"
  # Tell iTerm2 to use the custom preferences in the directory
  defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
fi
