tap "homebrew/bundle"

cask "xquartz"
brew "bash"
brew "bash-completion@2"
brew "cmake"
brew "bat"
brew "coreutils"
brew "ctags"
brew "fontforge"
brew "gifsicle"
brew "git"
brew "nvm"
brew "python"
brew "ripgrep"
brew "fzf"
brew "entr"


# tap "go-delve/delve"
# brew "go"
# brew "golangci/tap/golangci-lint"


# dependencies for compiling neovim
#brew "luajit"

# dependencies for compiling tmux
brew "libevent"
brew "automake"
brew "pkg-config"
brew "utf8proc"

# dependencies for compiling kitty
brew "lcms2" 
brew "librsync"

# dependencies for compiling keepassxc
# this breaks harfbuzz which is used for kitty
# brew "qt"
# brew "libgcrypt"
# brew "libyubikey"
# brew "ykpers"
# brew "argon2"
# brew "libsodium"
# brew "qrencode"

brew "reattach-to-user-namespace"
brew "ruby", link: true
brew "terminal-notifier"
# brew "the_silver_searcher"
brew "urlview"
brew "wget"

cask "firefox"
# cask "google-chrome"
# cask "scroll-reverser"
# cask "slack"
cask "zsa-wally"
cask "kitty"

brew "homebrew-ffmpeg/ffmpeg/ffmpeg", args: ["with-fdk-aac"] 
